name: Agent Assignment
on:
  pull_request:
    types:
      - opened
jobs:
  assign-frontline-engineer:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Get Team Members
        id: team-members
        env:
          frontLine: ${{ vars.FRONT_LINE_USERS_LIST }}
        #TODO - Temporary solution - team member configuration should be dynamic
        run: |
          echo "::set-output name=members::$frontLine"
      - name: Get Next Team Member
        id: next-member
        run: |
          members=($(echo "${{ steps.team-members.outputs.members }}" | tr ',' '\n'))
          index=$(( (${GITHUB_RUN_NUMBER}-1) % ${#members[@]} ))
          next_member=${members[$index]}
          echo "::set-output name=next_member::$next_member"
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
